# Generated by Django 4.2.3 on 2023-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_message_room_remove_message_user_message_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=18),
        ),
    ]
